OPTIONS(DIRECT=TRUE, PARALLEL=FALSE)

UNRECOVERABLE

LOAD DATA

APPEND

INTO TABLE ds3.membership

FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'

TRAILING NULLCOLS

(CUSTOMERID integer external,
MEMBERSHIPTYPE integer external,
EXPIREDATE date "yyyy/mm/dd")
