OPTIONS(DIRECT=TRUE, PARALLEL=FALSE)

UNRECOVERABLE

LOAD DATA

APPEND

INTO TABLE ds3.reviews_helpfulness

FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'

TRAILING NULLCOLS

(REVIEW_HELPFULNESS_ID integer external,
REVIEW_ID integer external,
CUSTOMERID integer external,
HELPFULNESS integer external)
