use DS3;
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE ORDERLINES DISABLE KEYS;

LOAD DATA LOCAL INFILE "../../../data_files/orders/jan_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/feb_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/mar_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/apr_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/may_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/jun_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/jul_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/aug_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/sep_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/oct_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/nov_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/dec_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE ORDERLINES ENABLE KEYS;
SET UNIQUE_CHECKS=1;
SET FOREIGN_KEY_CHECKS=1;
