sqlldr ds3/ds3 CONTROL=jan_orderlines.ctl, LOG=jan_orderlines.log, BAD=jan_orderlines.bad, DATA=../../../data_files/orders/jan_orderlines.csv &
sqlldr ds3/ds3 CONTROL=feb_orderlines.ctl, LOG=feb_orderlines.log, BAD=feb_orderlines.bad, DATA=../../../data_files/orders/feb_orderlines.csv &
sqlldr ds3/ds3 CONTROL=mar_orderlines.ctl, LOG=mar_orderlines.log, BAD=mar_orderlines.bad, DATA=../../../data_files/orders/mar_orderlines.csv &
sqlldr ds3/ds3 CONTROL=apr_orderlines.ctl, LOG=apr_orderlines.log, BAD=apr_orderlines.bad, DATA=../../../data_files/orders/apr_orderlines.csv &
sqlldr ds3/ds3 CONTROL=may_orderlines.ctl, LOG=may_orderlines.log, BAD=may_orderlines.bad, DATA=../../../data_files/orders/may_orderlines.csv &
sqlldr ds3/ds3 CONTROL=jun_orderlines.ctl, LOG=jun_orderlines.log, BAD=jun_orderlines.bad, DATA=../../../data_files/orders/jun_orderlines.csv &
sqlldr ds3/ds3 CONTROL=jul_orderlines.ctl, LOG=jul_orderlines.log, BAD=jul_orderlines.bad, DATA=../../../data_files/orders/jul_orderlines.csv &
sqlldr ds3/ds3 CONTROL=aug_orderlines.ctl, LOG=aug_orderlines.log, BAD=aug_orderlines.bad, DATA=../../../data_files/orders/aug_orderlines.csv &
sqlldr ds3/ds3 CONTROL=sep_orderlines.ctl, LOG=sep_orderlines.log, BAD=sep_orderlines.bad, DATA=../../../data_files/orders/sep_orderlines.csv &
sqlldr ds3/ds3 CONTROL=oct_orderlines.ctl, LOG=oct_orderlines.log, BAD=oct_orderlines.bad, DATA=../../../data_files/orders/oct_orderlines.csv &
sqlldr ds3/ds3 CONTROL=nov_orderlines.ctl, LOG=nov_orderlines.log, BAD=nov_orderlines.bad, DATA=../../../data_files/orders/nov_orderlines.csv &
sqlldr ds3/ds3 CONTROL=dec_orderlines.ctl, LOG=dec_orderlines.log, BAD=dec_orderlines.bad, DATA=../../../data_files/orders/dec_orderlines.csv &
