OPTIONS(DIRECT=TRUE, PARALLEL=TRUE)

UNRECOVERABLE

LOAD DATA

APPEND

INTO TABLE ds3.orders

FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'

TRAILING NULLCOLS

(ORDERID integer external,
ORDERDATE date "yyyy/mm/dd", 
CUSTOMERID integer external,
NETAMOUNT decimal external,
TAX decimal external,
TOTALAMOUNT decimal external)
