OPTIONS(DIRECT=TRUE, PARALLEL=TRUE)

UNRECOVERABLE

LOAD DATA

APPEND

INTO TABLE ds3.orderlines

FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'

TRAILING NULLCOLS

(ORDERLINEID integer external,
ORDERID integer external,
PROD_ID integer external,
QUANTITY integer external,
ORDERDATE date "yyyy/mm/dd") 
