use DS3;
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE REVIEWS_HELPFULNESS DISABLE KEYS;

LOAD DATA LOCAL INFILE "../../../data_files/reviews/review_helpfulness.csv" INTO TABLE REVIEWS_HELPFULNESS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE REVIEWS_HELPFULNESS ENABLE KEYS;
SET UNIQUE_CHECKS=1;
SET FOREIGN_KEY_CHECKS=1;
