use DS3;
SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE CUST_HIST DISABLE KEYS;

LOAD DATA LOCAL INFILE "../../../data_files/orders/jan_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/feb_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/mar_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/apr_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/may_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/jun_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/jul_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/aug_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/sep_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/oct_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/nov_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "../../../data_files/orders/dec_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE CUST_HIST ENABLE KEYS;
SET UNIQUE_CHECKS=1;
SET FOREIGN_KEY_CHECKS=1;
